version: "3.5"
services:
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/apache:/var/log/apache2
      - ./:/var/www/html
    networks:
      - docker_workspace_network

  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - docker_workspace_network

  composer:
    container_name: composer
    image: composer/composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: install

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - ./:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - docker_workspace_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - 8085:80
    networks:
      - docker_workspace_network

  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

networks:
  docker_workspace_network: