version: "3.7"

networks:
  databases_database:
     external: true
     
services:
    # image project
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: support_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - default
            - databases_database
                
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: support_nginx
        ports: 
            - 8070:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:   
            - default
            - databases_database
            
    #Node Service
    nodejs:
        image: node:lts-alpine
        container_name: support_nodejs
        restart: unless-stopped
        tty: true
        volumes:
        - ./:/var/www
        networks:
            - default
            - databases_database
        entrypoint: ['npm']



